version: '3.7'
services:

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    # networks:
    #   - backend-network
    ports:
      - '6789:6789'
    

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    network_mode: host
    depends_on: 
      - server
